# my global config
global:
  scrape_interval: 30s # Set the scrape interval to every 30 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 30 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "flask-api"
    scrape_interval: 10s
    static_configs:
      - targets: ["flask_api:8082"]

  - job_name: "flask-api-canary"
    scrape_interval: 10s
    static_configs:
      - targets: ["flask_api_canary:8082"]

  - job_name: "traefik"
    scrape_interval: 10s
    static_configs:
      - targets: ["traefik:8080"]

  - job_name: kafka-consumer
    static_configs:
      - targets: ["kafka-consumer:8000"]

  - job_name: redis-exporter
    static_configs:
      - targets: ["redis-exporter:9121"]

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ["alertmanager:9093"]
