# my global config
global:
  scrape_interval: 30s # Set the scrape interval to every 30 seconds. Default is every 1 minute.
  evaluation_interval: 30s # Evaluate rules every 30 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "flask-api"
    scrape_interval: 10s
    static_configs:
      - targets: ["172.16.238.10:8082"]

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ["172.16.238.13:9093"]
